import json
import os

img_id = 000000

data = {}
data['info'] = []
data['info'].append({
    'description': 'Annotation file generated by the Icopi tool.'
    })

data['licenses'] = []
data['licenses'].append({
    'url': 'http://creativecommons.org/licenses/by-nc-sa/2.0/',
    'id': 1,
    'name': 'Attribution-NonCommercial-ShareAlike License'
    })

data['images'] = []

filepath = '/data/training/bgs/'
for img_name in os.listdir(('..' + filepath)):
    data['images'].append({
        'license': 1,
        'file_name': img_name,
        'id': img_id
    })

    img_id += 1

data['annotations'] = []
annot_id = img_id
img_id = 0

filepath = '/data/training/palettes/'
for rgb_name in os.listdir(('..' + filepath)):
    path = ".." + filepath + rgb_name
    with open(path, 'r') as f:
        infile = f.read().replace('[', '').replace(']', '').split('\n')
    f.close()

    for entry in infile:
        entry = entry.strip()
        entry = ' '.join(entry.split())
        
        data['annotations'].append({
            'image_id': img_id,
            'id': annot_id,
            'caption': entry
        })

        annot_id += 1


    img_id += 1

filepath = '..//data/training/palettes/'
writefile = 'annotations.json'
path = filepath + writefile

with open(path, 'w+') as outfile:
    json.dump(data, outfile)
